In [79]:
#imports
import pandas as pd
import matplotlib.pyplot as plt

## Importing Dataset and Creating DataFrame

In [34]:
#load US Dataset
df = pd.read_csv("USM00072712-data.txt", sep = '\t', header = None)

In [35]:
df

                                                        0
0       #USM00072712 2021 01 01 00 2303  178 ncdc-nws ...
1       21     0  99364B  191   -32B  680    51   295 ...
2       20     8  98805   236B  -31B  594    68   296 ...
3       20    46  96285   440B  -45B  612    63   296 ...
4       10   154  92500   754B  -73B  663    52   298 ...
...                                                   ...
395232  20  9925   1210 29467B -559B   30   239    58 ...
395233  20  9938   1194 29553B -557B   29   241    54 ...
395234  20  9945   1186 29596B -556B   30   241    51 ...
395235  20  9952   1177 29643B -555B   30   240    58 ...
395236  20 10013   1159 29762B -556B   29   242    71 ...

[395237 rows x 1 columns]

In [63]:
#Assigning columns
id_ = []
year = []
month = []
day = []
hour =[]
reltime = []
numlev = []
p_src = []
np_src = []
lat = []
lon = []

lvltyp1 = []
lvltyp2 = []
etime = []
press = []
pflag = []
gph = []
zflag = []
temp = []
tflag = []
rh = []
dpdp = []
wdir = []
wspd = []

for line in df[0]:
    if "USM00072712" in line:
        id_.append(line[0:12].strip())
        year.append(line[13:17].strip())
        month.append(line[18:20].strip())
        day.append(line[21:23])
        hour.append(line[24:26])
        reltime.append(line[27:31])
        numlev.append(line[33:36])
        p_src.append(line[37:45])
        np_src.append(line[46:54])
        lat.append(line[56:62])
        lon.append(line[64:71])
        lvltyp1.append(None)
        lvltyp2.append(None)
        etime.append(None)
        press.append(None)
        pflag.append(None)
        gph.append(None)
        zflag.append(None)
        temp.append(None)
        tflag.append(None)
        rh.append(None)
        dpdp.append(None)
        wdir.append(None)
        wspd.append(None)
    else:
        id_.append(None)
        year.append(None)
        month.append(None)
        day.append(None)
        hour.append(None)
        reltime.append(None)
        numlev.append(None)
        p_src.append(None)
        np_src.append(None)
        lat.append(None)
        lon.append(None)
        lvltyp1.append(line[0:1].strip())
        lvltyp2.append(line[1:2].strip())
        etime.append(line[4:8].strip())
        press.append(line[10:15].strip())
        pflag.append(line[15:16].strip())
        gph.append(line[17:21].strip())
        zflag.append(line[21:22].strip())
        temp.append(line[23:27].strip())
        tflag.append(line[27:28].strip())
        rh.append(line[29:33].strip())
        dpdp.append(line[35:39].strip())
        wdir.append(line[41:45].strip())
        wspd.append(line[47:51].strip())

In [64]:
#Creating DataFrame
us_df = pd.DataFrame({
    'id_': id_,
    'year': year,
    'month': month,
    'day': day,
    'hour': hour,
    'reltime': reltime,
    'numlev': numlev,
    'p_src': p_src,
    'np_src': np_src,
    'lat': lat,
    'lon': lon,
    'lvltyp1': lvltyp1,
    'lvltyp2': lvltyp2,
    'etime': etime,
    'press': press,
    'pflag': pflag,
    'gph': gph,
    'zflag': zflag,
    'temp': temp,
    'tflag': tflag,
    'rh': rh,
    'dpdp': dpdp,
    'wdir': wdir,
    'wspd': wspd})

In [66]:
#Combining Headers with variables
us_df['id_'].fillna(method = 'ffill', inplace = True)
us_df['year'].fillna(method = 'ffill', inplace = True)
us_df['month'].fillna(method = 'ffill', inplace = True)
us_df['day'].fillna(method = 'ffill', inplace = True)
us_df['hour'].fillna(method = 'ffill', inplace = True)
us_df['reltime'].fillna(method = 'ffill', inplace = True)
us_df['numlev'].fillna(method = 'ffill', inplace = True)
us_df['p_src'].fillna(method = 'ffill', inplace = True)
us_df['np_src'].fillna(method = 'ffill', inplace = True)
us_df['lat'].fillna(method = 'ffill', inplace = True)
us_df['lon'].fillna(method = 'ffill', inplace = True)

In [67]:
#Drop rows with null values
us_df = us_df.dropna()

In [68]:
us_df

,id_,year,month,day,hour,reltime,numlev,p_src,np_src,lat,...,press,pflag,gph,zflag,temp,tflag,rh,dpdp,wdir,wspd
1,#USM00072712,2021,01,01,00,2303,178,ncdc-nws,ncdc-nws,468683,...,99364,B,191,,-32,B,680,51,295,36
2,#USM00072712,2021,01,01,00,2303,178,ncdc-nws,ncdc-nws,468683,...,98805,,236,B,-31,B,594,68,296,47
3,#USM00072712,2021,01,01,00,2303,178,ncdc-nws,ncdc-nws,468683,...,96285,,440,B,-45,B,612,63,296,96
4,#USM00072712,2021,01,01,00,2303,178,ncdc-nws,ncdc-nws,468683,...,92500,,754,B,-73,B,663,52,298,127
5,#USM00072712,2021,01,01,00,2303,178,ncdc-nws,ncdc-nws,468683,...,91875,,807,B,-78,B,676,49,299,124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395232,#USM00072712,2024,02,03,12,1103,321,ncdc-nws,,468683,...,1210,,9467,B,-559,B,30,239,58,77
395233,#USM00072712,2024,02,03,12,1103,321,ncdc-nws,,468683,...,1194,,9553,B,-557,B,29,241,54,72
395234,#USM00072712,2024,02,03,12,1103,321,ncdc-nws,,468683,...,1186,,9596,B,-556,B,30,241,51,69
395235,#USM00072712,2024,02,03,12,1103,321,ncdc-nws,,468683,...,1177,,9643,B,-555,B,30,240,58,64
395236,#USM00072712,2024,02,03,12,1103,321,ncdc-nws,,468683,...,1159,,9762,B,-556,B,29,242,71,55

Data Cleaning
-Null values

#Functions:
-Temperature convert to farenheit
-Relative humidity to ice
-Pressure to pressure altitude
-add additional columns from calculations
-Filter data: Filter date, pressure altitude to 4,300
-Capture when temp is below -42, RH above 100%, and altitude below 4,300

-Capture dpdp, wdir, wspd. No calculation needed

In [71]:
#Loading Canadian Dataset
df2 = pd.read_csv("CAM00071701-data.txt", sep = '\t', header = None)

In [72]:
df2

                                                       0
0      #CAM00071701 2021 01 26 12 1011   69 ncdc-gts ...
1      21 -9999 100800B-9999   -57B-9999    30   275 ...
2      10 -9999 100000   116B  -63B-9999    19   285 ...
3      20 -9999  97700 -9999   -73B-9999     7 -9999 ...
4      20 -9999  94700 -9999   -39B-9999    10 -9999 ...
...                                                  ...
18003  30 -9999  -9999  4200 -9999 -9999 -9999   265 ...
18004  30 -9999  -9999  5100 -9999 -9999 -9999   275 ...
18005  30 -9999  -9999  5700 -9999 -9999 -9999   280 ...
18006  30 -9999  -9999  6000 -9999 -9999 -9999   280 ...
18007  30 -9999  -9999 12000 -9999 -9999 -9999   295 ...

[18008 rows x 1 columns]

In [73]:
#Assigning columns
id_2 = []
year2 = []
month2 = []
day2 = []
hour2 =[]
reltime2 = []
numlev2 = []
p_src2 = []
np_src2 = []
lat2 = []
lon2 = []

lvltyp12 = []
lvltyp22 = []
etime2 = []
press2 = []
pflag2 = []
gph2 = []
zflag2 = []
temp2 = []
tflag2 = []
rh2 = []
dpdp2 = []
wdir2 = []
wspd2 = []

for line in df2[0]:
    if "CAM00071701" in line:
        id_2.append(line[0:12].strip())
        year2.append(line[13:17].strip())
        month2.append(line[18:20].strip())
        day2.append(line[21:23])
        hour2.append(line[24:26])
        reltime2.append(line[27:31])
        numlev2.append(line[33:36])
        p_src2.append(line[37:45])
        np_src2.append(line[46:54])
        lat2.append(line[56:62])
        lon2.append(line[64:71])
        lvltyp12.append(None)
        lvltyp22.append(None)
        etime2.append(None)
        press2.append(None)
        pflag2.append(None)
        gph2.append(None)
        zflag2.append(None)
        temp2.append(None)
        tflag2.append(None)
        rh2.append(None)
        dpdp2.append(None)
        wdir2.append(None)
        wspd2.append(None)
    else:
        id_2.append(None)
        year2.append(None)
        month2.append(None)
        day2.append(None)
        hour2.append(None)
        reltime2.append(None)
        numlev2.append(None)
        p_src2.append(None)
        np_src2.append(None)
        lat2.append(None)
        lon2.append(None)
        lvltyp12.append(line[0:1].strip())
        lvltyp22.append(line[1:2].strip())
        etime2.append(line[4:8].strip())
        press2.append(line[10:15].strip())
        pflag2.append(line[15:16].strip())
        gph2.append(line[17:21].strip())
        zflag2.append(line[21:22].strip())
        temp2.append(line[23:27].strip())
        tflag2.append(line[27:28].strip())
        rh2.append(line[29:33].strip())
        dpdp2.append(line[35:39].strip())
        wdir2.append(line[41:45].strip())
        wspd2.append(line[47:51].strip())

In [74]:
#Creating DataFrame
can_df = pd.DataFrame({
    'id_': id_2,
    'year': year2,
    'month': month2,
    'day': day2,
    'hour': hour2,
    'reltime': reltime2,
    'numlev': numlev2,
    'p_src': p_src2,
    'np_src': np_src2,
    'lat': lat2,
    'lon': lon2,
    'lvltyp1': lvltyp12,
    'lvltyp2': lvltyp22,
    'etime': etime2,
    'press': press2,
    'pflag': pflag2,
    'gph': gph2,
    'zflag': zflag2,
    'temp': temp2,
    'tflag': tflag2,
    'rh': rh2,
    'dpdp': dpdp2,
    'wdir': wdir2,
    'wspd': wspd2})

In [75]:
#Combining Headers with variables
can_df['id_'].fillna(method = 'ffill', inplace = True)
can_df['year'].fillna(method = 'ffill', inplace = True)
can_df['month'].fillna(method = 'ffill', inplace = True)
can_df['day'].fillna(method = 'ffill', inplace = True)
can_df['hour'].fillna(method = 'ffill', inplace = True)
can_df['reltime'].fillna(method = 'ffill', inplace = True)
can_df['numlev'].fillna(method = 'ffill', inplace = True)
can_df['p_src'].fillna(method = 'ffill', inplace = True)
can_df['np_src'].fillna(method = 'ffill', inplace = True)
can_df['lat'].fillna(method = 'ffill', inplace = True)
can_df['lon'].fillna(method = 'ffill', inplace = True)

In [76]:
#Drop rows with null values
can_df = can_df.dropna()

In [77]:
can_df

,id_,year,month,day,hour,reltime,numlev,p_src,np_src,lat,...,press,pflag,gph,zflag,temp,tflag,rh,dpdp,wdir,wspd
1,#CAM00071701,2021,01,26,12,1011,69,ncdc-gts,ncdc-gts,458333,...,00800,B,9999,,-57,B,9999,30,275,31
2,#CAM00071701,2021,01,26,12,1011,69,ncdc-gts,ncdc-gts,458333,...,00000,,116,B,-63,B,9999,19,285,46
3,#CAM00071701,2021,01,26,12,1011,69,ncdc-gts,ncdc-gts,458333,...,97700,,9999,,-73,B,9999,7,9999,9999
4,#CAM00071701,2021,01,26,12,1011,69,ncdc-gts,ncdc-gts,458333,...,94700,,9999,,-39,B,9999,10,9999,9999
5,#CAM00071701,2021,01,26,12,1011,69,ncdc-gts,ncdc-gts,458333,...,93100,,9999,,-51,B,9999,0,9999,9999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18003,#CAM00071701,2024,01,25,06,0520,47,ncdc-gts,ncdc-gts,458333,...,-9999,,4200,,9999,,9999,9999,265,185
18004,#CAM00071701,2024,01,25,06,0520,47,ncdc-gts,ncdc-gts,458333,...,-9999,,5100,,9999,,9999,9999,275,195
18005,#CAM00071701,2024,01,25,06,0520,47,ncdc-gts,ncdc-gts,458333,...,-9999,,5700,,9999,,9999,9999,280,324
18006,#CAM00071701,2024,01,25,06,0520,47,ncdc-gts,ncdc-gts,458333,...,-9999,,6000,,9999,,9999,9999,280,340
18007,#CAM00071701,2024,01,25,06,0520,47,ncdc-gts,ncdc-gts,458333,...,-9999,,2000,,9999,,9999,9999,295,895